num1=int(input("enter the number"))
num2=int(input("enter the number"))
num3=int(input("enter the number"))
print("the sum of num1 and num2 is:",num1+num2)
print("The difference when num2 is subtracted from num1 is:",num1-num2)
print("The quotient when num1 is divided by num2 is:",num1/num2)
print("The product of num1 and num2 is:",num1*num2)
print("The reminder when num1 is divided num2 is:",num1%num2)
print("the result of (num1+num2)*num3/2 is :",(num1+num2)*num3/2)
